### ISSUE TITLE
do you have any mp4 repair tools?

### ISSUE THREAD

**Issue by cellurl3** [TheDiveO/kdenlive-project-analyzer#1]
sorry to ask this way......

**Comment by thediveo** [comment]
Years ago when using IMHO terribly buggy Hero cameras, I had a need to repair diving footage in MP4 containers. I had some success using a repair software from a German company called "Grau GmbH", that was the only one out of several ones I tried being able to salvage the damage to some extent that GoPros shoddy software and hardware caused on several occasions, and on several cameras and memory cards.

The problem with video formats is that they need to be optimized for speed and limited resources at the same time, so tools are limited as to what they can do. For me, the investment in a semi-pro Cannon XF30 camera (with bulky diving case) solved the general issues with especially GoPro and SanDisk products, as the Cannon semi-pro has dual SD card slots (not mSD for good reasons) with a beefy buffer RAM and a card controller that can write two cards simultaneously. I threw really shoddy SD Extreme Pro Plus whatever cards made by SanDisk at it and it managed to correctly and reliably write to these rather expensive cards,  which are often failing in many other cameras. The real world writing performance of SanDisk mSD and SD cards is often completely unreliable, contrary to their marketing claims.

**Comment by cellurl3** [comment]
thanks for that. I will try Grau GmbH !
The video was special, worth paying a bit to recover it....
